version: '3.6'
services:
  phoenix:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - .:/turnify
    depends_on:
      - db
    command: ./script/start_dev.sh
  db:
    restart: always
    image: postgres:latest
    command: 'postgres -c "max_connections=200"'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=5AsVtJk8aX
      - POSTGRES_USER=turnify_dev
    volumes:
      - db:/var/lib/postgresql/data

volumes:
    db:
      driver: local
